name: worldcom_finance
description: App for Worldcom Finance.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # getX
  get: ^4.6.5

  # gap for spacing
  gap: ^2.0.1

  # svg loader
  flutter_svg: 2.0.3

  # cache network image
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0

  # shared pref
  shared_preferences: ^2.0.18

  # secure shared pref
  flutter_secure_storage: ^8.0.0

  # for internet connectivity
  connectivity_plus: ^3.0.3

  # device and package info
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3

  # to get android device ID
  android_id: ^0.1.3+1

  # network API calling
  retrofit: ^4.0.1
  dio: ^5.0.2
  json_annotation: ^4.8.0

  # otp field
  pin_code_fields: ^7.4.0
  flutter_otp_text_field: ^1.1.1

  # local authentication - biometric
  local_auth: ^2.1.6

  # country picker
  country_picker: ^2.0.20

  # image picker from camera or gallery
  image_picker: ^0.8.7

  # date picker
  scroll_date_picker: ^3.7.0

  # to open url
  url_launcher: ^6.1.10

  # SMS Autofill
  sms_autofill: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  injectable_generator: ^2.1.4
  retrofit_generator: ^6.0.0+1
  json_serializable: ^6.6.1


flutter_gen:
  integrations:
    flutter_svg: true


flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: SFCompactDisplay
      fonts:
        - asset: assets/fonts/SFCompactDisplay-Regular.ttf
